# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogIn():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_logIn(self):
    # Test name: logIn
    # Step # | name | target | value
    # 1 | open | /?fromurl=http%3A%2F%2Fcrm.test.k8s.ustax.com.cn%2F | 
    self.driver.get("http://sso.test.k8s.ustax.com.cn/?fromurl=http%3A%2F%2Fcrm.test.k8s.ustax.com.cn%2F")
    # 2 | setWindowSize | 1936x1056 | 
    self.driver.set_window_size(1936, 1056)
    # 3 | click | css=.el-form-item:nth-child(1) .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(1) .el-input__inner").click()
    # 4 | type | css=.el-form-item:nth-child(1) .el-input__inner | 17585571191
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(1) .el-input__inner").send_keys("17585571191")
    # 5 | click | css=.el-form-item:nth-child(2) .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(2) .el-input__inner").click()
    # 6 | click | css=.el-form-item:nth-child(2) .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(2) .el-input__inner").click()
    # 7 | type | css=.el-form-item:nth-child(2) .el-input__inner | resicoit999
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(2) .el-input__inner").send_keys("resicoit999")
    # 8 | click | css=.v-button-ok | 
    self.driver.find_element(By.CSS_SELECTOR, ".v-button-ok").click()
    # 9 | click | css=.el-submenu:nth-child(3) .v-menu-container_submenu_text | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-submenu:nth-child(3) .v-menu-container_submenu_text").click()
    # 10 | click | css=.el-menu-item:nth-child(2) span | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-menu-item:nth-child(2) span").click()
    # 11 | mouseOver | linkText=私有库 | 
    element = self.driver.find_element(By.LINK_TEXT, "私有库")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 12 | click | css=.el-button--primary:nth-child(3) > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-button--primary:nth-child(3) > span").click()
    # 13 | click | css=.el-form > .el-form-item > .el-form-item__content > .el-input > .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-form > .el-form-item > .el-form-item__content > .el-input > .el-input__inner").click()
    # 14 | click | css=.is-error .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".is-error .el-input__inner").click()
    # 15 | type | css=.is-error .el-input__inner | 私有库新增录制用户二
    self.driver.find_element(By.CSS_SELECTOR, ".is-error .el-input__inner").send_keys("私有库新增录制用户二")
    # 16 | type | css=.el-input-group > .el-input__inner | 152108293333
    self.driver.find_element(By.CSS_SELECTOR, ".el-input-group > .el-input__inner").send_keys("152108293333")
    # 17 | click | css=.is-error .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".is-error .el-input__inner").click()
    # 18 | type | css=.is-error .el-input__inner | 私有库新增录制用户三
    self.driver.find_element(By.CSS_SELECTOR, ".is-error .el-input__inner").send_keys("私有库新增录制用户三")
    # 19 | click | css=.is-focus > .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".is-focus > .el-input__inner").click()
    # 20 | click | css=.hover | 
    self.driver.find_element(By.CSS_SELECTOR, ".hover").click()
    # 21 | click | css=.el-cascader .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-cascader .el-input__inner").click()
    # 22 | click | css=#cascader-menu-812-0-2 > .el-cascader-node__label | 
    self.driver.find_element(By.CSS_SELECTOR, "#cascader-menu-812-0-2 > .el-cascader-node__label").click()
    # 23 | click | css=#cascader-menu-8537-1-2 > .el-cascader-node__label | 
    self.driver.find_element(By.CSS_SELECTOR, "#cascader-menu-8537-1-2 > .el-cascader-node__label").click()
    # 24 | click | css=#cascader-menu-1029-2-1 > .el-cascader-node__label | 
    self.driver.find_element(By.CSS_SELECTOR, "#cascader-menu-1029-2-1 > .el-cascader-node__label").click()
    # 25 | click | css=.el-textarea__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-textarea__inner").click()
    # 26 | type | css=.el-textarea__inner | 123号
    self.driver.find_element(By.CSS_SELECTOR, ".el-textarea__inner").send_keys("123号")
    # 27 | click | css=.el-form-item:nth-child(8) .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(8) .el-input__inner").click()
    # 28 | click | css=.hover:nth-child(7) | 
    self.driver.find_element(By.CSS_SELECTOR, ".hover:nth-child(7)").click()
    # 29 | click | css=.el-button:nth-child(3) > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-button:nth-child(3) > span").click()
    # 30 | close |  | 
    self.driver.close()
    # 31 | close |  | 
    self.driver.close()


if __name__ == '__main__':
  pytest.main('-v', "test_logIn.py")
